### ISSUE TITLE
Phasorite mod crash

### ISSUE THREAD

**Issue by Gianni1707** [milosworks/phasorite-networks#2]
### Issue Description

every time I use/place/break a phasorite block importer and exporter the server crashes

### Mod Version

0.0.1-beta

### Priority this issue should have

High (immediate attention needed)

### Your latest.log

[15:18:30] [Server thread/INFO] [Prefab/]: Super17__ logged into server, sending config to client [15:18:30] [Netty Epoll Server IO #3/WARN] [io.ne.ut.co.DefaultPromise/]: An exception was thrown by net.minecraft.network.Connection$$Lambda/0x00007f7205542da0.operationComplete() java.util.NoSuchElementException: DefaultChannelPipeline$TailContext#0         at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}         at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.mddc5a68$connectivity$lambda$on$0$2(Connection.java:1326) ~[server-1.21.1-20240808.144430-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}         at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:185) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}         at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.Connection.mddc5a68$connectivity$lambda$on$1$1(Connection.java:1304) ~[server-1.21.1-20240808.144430-srg.jar%23285!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}         at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:990) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.transport@4.1.97.Final/io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:823) ~[netty-transport-4.1.97.Final.jar%23108!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.transport.classes.epoll@4.1.97.Final/io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:416) ~[netty-transport-classes-epoll-4.1.97.Final.jar%23109!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}         at MC-BOOTSTRAP/io.netty.common@4.1.97.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar%23105!/:4.1.97.Final] {}         at java.base/java.lang.Thread.run(Thread.java:1570) [?:?] {re:mixin} [15:18:30] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: Super17__ lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:update_recipes' [15:18:30] [Server thread/INFO] [minecraft/MinecraftServer]: Super17__ left the game

**Comment by milosworks** [comment]
This is something..., is this in single player or server?

**Comment by milosworks** [comment]
Also are you sure the mod is on both client and server side?

**Comment by Gianni1707** [comment]
> Also are you sure the mod is on both client and server side?

Yes.And i play on a server

**Comment by milosworks** [comment]
it could help a lot more if upload the crash report and the latest log to https://mclo.gs/ do not copy the content just copy paste the file

**Comment by milosworks** [comment]
Sorry just to continue to investigate about this crash as this hasnt happened and i need the latest.log/crash.log complete

**Comment by Gianni1707** [comment]
Hi,sorry for yesterday I had some issues with others mod...so,today I place a phasorite importer and server crashes.I send you the log,i have the crashing report,too (if you need it,idk how it works).

**Comment by Gianni1707** [comment]
> Hi,sorry for yesterday I had some issues with others mod...so,today I place a phasorite importer and server crashes.I send you the log,i have the crashing report,too (if you need it,idk how it works).

[Uploading crash-2025-01-02_09.57.37-server.txt…]()

**Comment by Gianni1707** [comment]
> > Hi,sorry for yesterday I had some issues with others mod...so,today I place a phasorite importer and server crashes.I send you the log,i have the crashing report,too (if you need it,idk how it works).
> 
> Uploading crash-2025-01-02_09.57.37-server.txt…

the latest log is in  https://mclo.gs/

**Comment by milosworks** [comment]
> > > Hi,sorry for yesterday I had some issues with others mod...so,today I place a phasorite importer and server crashes.I send you the log,i have the crashing report,too (if you need it,idk how it works).
> > 
> > 
> > Uploading crash-2025-01-02_09.57.37-server.txt…
> 
> the latest log is in https://mclo.gs/

Hey so u need to send the links from the mclo.gs website for the crash report and the latest log as the crash report u sent in plain text is a little bit unreadable, thanks so much

**Comment by Gianni1707** [comment]
ok,i think this time is correct,sorry for my mistakes. https://mclo.gs/Ma6M0Iw

**Comment by milosworks** [comment]
This (should be fixed) is fixed on v0.0.4-beta

**Comment by Gianni1707** [comment]
Ok,i test it.Thank you for the support
